
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:

  LambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: aws-lambda
      CodeUri: target/aws-lambda-0.0.1-SNAPSHOT.jar
      Handler: com.test.awslambda.LambdaHandler::handleRequest
      Runtime: java11
      MemorySize: 512
    Events:
      GatewayApi:
        Type: Api

